version: 2
jobs:
  build:
    working_directory: ~/pizzaiols
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
    deploy:
      working_directory: ~/pizzaiols
      docker:
        - image: node:8.10.0
      steps:
        - add_ssh_keys:
            fingerprints:
              - 'aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa'
        - checkout
        - attach_workspace:
            at: ~/pizzaiols
        - run:
            name: Install gh-pages
            command: |
              npm install -g --silent gh-pages
        - run:
            name: Configure git
            command: |
              git config user.email "ruslanusm6@gmail.com"
              git config user.name "owlruslan"
        - run:
            name: Deploy to gh-pages branch
            command: gh-pages --message "[ci skip]" -d dist


workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
